### ISSUE TITLE
Helping out...

### ISSUE THREAD

**Issue by boermansjo** [ESX-Org/es_extended2#1]
Hello,

I just read the issue with Kanersps. He was always butthurt.
He was the main reason why I discontinued my server and scripts. (See the repos on my account)
I also have proof that when he released his essentialmode there was no license.
Not sure if that helps. And I also don't know if you can add a license AFTER releasing code..
(These files can also be found in a discontinued repo)
![image](https://user-images.githubusercontent.com/582664/80256854-eb9b1800-867f-11ea-9809-2f549105738a.png)
![image](https://user-images.githubusercontent.com/582664/80256880-f8b80700-867f-11ea-92ac-ed506d25f30a.png)
These files are from 3 years ago when he just finished the switch from MySQL to NoSQL
I try to give you some information that may or may not help. This guy made lifes difficult in the past already and I don't want to see this work taken down by people like him.

**Comment by kanersps** [comment]
According to: https://choosealicense.com/no-permission/

Not having a license is even worse

**Comment by boermansjo** [comment]
Ow yeah. I assumed that hosting it on GitHub you accepted their terms. But didn't looked at the user part. Hmm well this was a really ancient version. Probably not really helpful in this case anyways. The code was completely changed after that.

**Comment by ElPumpo** [comment]
Dont know where kanersps got the guts to keep comment on this. For your information even I dont know what files github are acting on.

Kanersps is so fucking jelous that we ditched his code, and thinks we used any of his code when we havent. Embarresing for sure

**Comment by ElPumpo** [comment]
Maybe havent made it clear yet kanersps doesnt own any of the files and none of the code belongs to him. He is so fucking disgusting really, like how the fuck was he even able to claim dmca function NAMES and parameter NAMES becsuse thats all he has. I know kanersps gonna read this wanna let you know you are the biggest fucking loser ever and you know it

**Comment by boermansjo** [comment]
He has done it in the past, it seems that he don't learn from his mistakes...
I hope you guys manage to revert the takedown.
Most are sick to see en use this crappy nosql.
This version was en is still far better. It is time to change in the FiveM community...

**Comment by Scullyy** [comment]
> 
> 
> Maybe havent made it clear yet kanersps doesnt own any of the files and none of the code belongs to him. He is so fucking disgusting really, like how the fuck was he even able to claim dmca function NAMES and parameter NAMES becsuse thats all he has. I know kanersps gonna read this wanna let you know you are the biggest fucking loser ever and you know it

You mentioned that he is trying to get people to swap over to extendedmode but why don't you just get that taken down for copying your code.

**Comment by d0p3t** [comment]
If you are unsure what the DMCA request was exactly for, the information is made publicly available by Github https://github.com/github/dmca/commit/28ea488cc457998c5dac45624ed45442e05efaee

**Comment by ElPumpo** [comment]
@d0p3t open your mouth one more time and you'll find a hammer in it

**Comment by ElPumpo** [comment]
![image](https://user-images.githubusercontent.com/12564301/80275599-ac51e300-86e2-11ea-95b0-5bda3cccab2b.png)
and dont worry you little hater we already found something that will make kane drop everything

**Comment by bigblackafricanman** [comment]
> Dont know where kanersps got the guts to keep comment on this
Why the fuck do you think you're above everyone else?

**Comment by indilo53** [comment]
Actually he is not the one playing god rn

**Comment by bigblackafricanman** [comment]
`You have no permission from the creators of the software to use, modify, or share the software. Although a code host such as GitHub may allow you to view and fork the code, this does not imply that you are permitted to use, modify, or share the software for any purpose.` I think you miss the point of no license as well

**Comment by ElPumpo** [comment]
@bigblackafricanman i dont need to think, i already am. Tell me how blacklisting esx went

**Comment by boermansjo** [comment]
It doesn't matter... there is a license now. He is just trying to cover his ass because he probably has some deal with ZAP-hosting (they are forcing you to always use the latest essentialmode) probably paying him a little.. If everyone is going to start using this one and drop all his stuff, well guess what happens... no more users, no money, no patreon.

**Comment by ElPumpo** [comment]
Woops accedently slipped my finger

**Comment by ElPumpo** [comment]
here's some quick facts:
- i have rights to copy code (and much more) from  https://github.com/kanersps/essentialmode/tree/0b7285e494fb6943c0a39e2eed3d2bd02992523a as i am a copyright holder
- we dont know why kanersps would do such a low thing. if you look what he's saying to people they are all celebrating yet for some reasons they say we're assholes. the same people celebrating are the people who started this attitude way back yet according to themselves i started it. doing dmcas is crossing a line, why do you even share any code in a modding community if you gonna behave like a complete dick.
- kanersps keeps saying that he cares about esx. but if he did he would've never done this dmca, especally since the original dmca wanted a) the entire repositorry deleted b) credit for "his work" he didn't even link. furthermore kanersps is lying in conversations with him (check esx discord for proof) on how he attempted to contact me in order to resolve the issue before claiming dmca. when we asked him for proof he kept changing subject and there's nothing in pms with him that confirms this. basicly kanersps is lying about that
- dmca will keep it down esx for permanate, unless you counter dmca. we have counter dmca which means unless kanersps takes this to court within 2 weeks esx will be back
- kanersps is lying in his dmca saying how he owns parts of code that are 100% original. the similarities are because we had to implement code that had the exact same featues. how you gonna go standalone if the code you're trying to ditch is needed, a perfect example is command handling.
- the only file you'd think kanersps "owns" in any way is the player.lua file. but understand that he shared a file **concept** on how "class" file should've been looking like. he cant claim dmca on that. even if he is then im a copyright holder from the code linked above so we don't give a fuck anyways. go look in his dmca request he is marking code that i fucking developed as his just because they do the same, and you might think its suspicious but fucking understand we must implement code that does the exact same.
- kanersps is lying to github about his project being licensed under AGPLv3. in the code above there's no license meaning it's licensed under "nolicense" - google it

you think our attitude is bad? go look in the fivem discord and gay 🤢 kanersps discord they are all celebrating about this invalid dmca. just wait after 2 weeks we'll see if there's no consequenses to what happend

**Comment by ElPumpo** [comment]
if @d0p3t's boyfriends also gonna start comment go ahead gonna destroy all of your arguments. i swear come test with some arguments on how im wrong gonna get put to sleep

**Comment by hichay** [comment]
Is this get problem with the Registerfont file ? i up stream font inside the ESX. and now my server get full square on text

**Comment by SSNRSS** [comment]
> Is this get problem with the Registerfont file ? i up stream font inside the ESX. and now my server get full square on text And everytime i start the server. the ESX got stopping and restart again. i think fivem is doing something to make ESX stop!

yeah look at esx discord announcements.

**Comment by hichay** [comment]
> > Is this get problem with the Registerfont file ? i up stream font inside the ESX. and now my server get full square on text And everytime i start the server. the ESX got stopping and restart again. i think fivem is doing something to make ESX stop!
> 
> yeah look at esx discord announcements.

well it still name es_extended. everytime start server fivem try to stop it. this wont help. all the Font register in ESX got error. Some resource not start when start server. Fuck kaner

**Comment by boermansjo** [comment]
All the claims are bullshit... Like I said before, they are afraid to lose patreons and or donations and partnerships (ZAP-hosting)
And kanersps is a mod on the forum too so he will always talk good about his half assed project.
3 years ago I already had a discussion about all this.
After seeing this work I had some hope again. But nothing has changed it seems.
Why does Fivem even support this stuff ?
What is the difference of using essentialmode or that CCore framework ? Will they ban that too because it doesn't make profit ?
What if I spend time and create a new framework from scratch without essentialmode will it be blocked too ? Where is the freedom in creating scripts for others ?

**Comment by bigblackafricanman** [comment]
so are you saying all these other servers that dont use esx aren't being targeted because they make profit? stan mf

**Comment by hichay** [comment]
> so are you saying all these other servers that dont use esx aren't being targeted because they make profit? stan mf

exactly. when you use esx. your server will sometime get error

**Comment by boermansjo** [comment]
> so are you saying all these other servers that dont use esx aren't being targeted because they make profit? stan mf

In one way or an other yes, but no...
Why is ESX being blocked and marked as "unrecommended server configuration" in the server lists ? but all those using CCore or vRP aren't ? Please explain it to me...

**Comment by indilo53** [comment]
Yo guys just dont register event and use factory pattern or do some sort of oop because kane owns the concept. Oh and dont update player coords to the server its also kane hard work
